### ISSUE TITLE
关于dynrefer中的val.json

### ISSUE THREAD

**Issue by 2629630207** [callsys/DynRefer#1]
您好，我使用coco进行eval，显示缺少标题中的json文件，请问这个文件中存的是img名称以及对应的box坐标吗？

**Comment by callsys** [comment]
你好！你可以补充上报错信息，这样我可以查看下缺少了什么文件

**Comment by 2629630207** [comment]
![1719282702872](https://github.com/callsys/DynRefer/assets/55966964/71a651aa-9ccf-4a1e-9965-8492c5cf7d36)

**Comment by 2629630207** [comment]
> 你好！你可以补充上报错信息，这样我可以查看下缺少了什么文件

![1719282702872](https://github.com/callsys/DynRefer/assets/55966964/1defedd5-80a0-4e58-8a77-3a650fa744b5)

**Comment by callsys** [comment]
你下载了数据集的标注文件吗，在这个链接[data.zip](https://mailsucasaccn-my.sharepoint.com/personal/zhaoyuzhong20_mails_ucas_ac_cn/_layouts/15/onedrive.aspx?view=0&id=%2Fpersonal%2Fzhaoyuzhong20%5Fmails%5Fucas%5Fac%5Fcn%2FDocuments%2FDynRefer)。

**Comment by 2629630207** [comment]
> 你下载了数据集的标注文件吗，在这个链接[data.zip](https://mailsucasaccn-my.sharepoint.com/personal/zhaoyuzhong20_mails_ucas_ac_cn/_layouts/15/onedrive.aspx?view=0&id=%2Fpersonal%2Fzhaoyuzhong20%5Fmails%5Fucas%5Fac%5Fcn%2FDocuments%2FDynRefer)。

怪不得，我把这个漏了，非常感谢
